### ISSUE TITLE
JavaScript Track Courses to be completed

### ISSUE THREAD

**Issue by joshuaking85** [joshuaking85/Treehouse#2]
## TODO

_Courses left to complete the Treehouse JavaScript Track_
- [ ] JavaScript Loops, Arrays and Objects
- [ ] jQuery Basics
- [ ] Using jQuery Plugins
- [ ] Interactive Web Pages with JavaScript

👍  🏆
